version: '3.8'

services:
  postgres:
    container_name: postgres-orders
    image: postgres
    environment:
      POSTGRES_USER: ameda
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: orders
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - products-project
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - products-project
    restart: unless-stopped
#  mysql:
#    container_name: mysql-db
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: products
#      MYSQL_USER: ameda
#      MYSQL_PASSWORD: pass
#    volumes:
#      - mysql:/var/lib/mysql
#    ports:
#      - "3306:3306"
#    networks:
#      - products-project
#    restart: unless-stopped

networks:
  products-project:
    driver: bridge

volumes:
  postgres:
  pgadmin:
    driver: local
#  mysql:
